### ISSUE TITLE
git cz fails when not in the root directory

### ISSUE THREAD

**Issue by pmcelhaney** [commitizen/cz-cli#187]
When I try to run `git cz` and I'm not in the root directory I get an error. 

```sh
~/code/cz-cli/src (run-from-anywhere)
$ git cz
./node_modules/cz-conventional-changelog /Users/patrickmcelhaney/code/cz-cli/src
/usr/local/lib/node_modules/commitizen/dist/commitizen/adapter.js:185
    throw error;
    ^

Error: Could not resolve /Users/patrickmcelhaney/code/cz-cli/src/node_modules/cz-conventional-changelog
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at resolveAdapterPath (/usr/local/lib/node_modules/commitizen/dist/commitizen/adapter.js:182:20)
    at gitCz (/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:77:35)
    at Object.bootstrap (/usr/local/lib/node_modules/commitizen/dist/cli/git-cz.js:32:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/commitizen/bin/git-cz.js:2:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by ta2edchimp** [comment]
A mixture of how we [detect the current git repo's root](https://github.com/gtramontina/ghooks/blob/master/lib/install.js#L43-L50) and [resolve the path to a required module](https://github.com/gtramontina/ghooks/pull/69/commits/ee8b2cd173158cc0a162f4f60abb812a6cab3e94#diff-07a81d82ccc03cfdbbdb8416bdbd89f8R13) using [`findup`](https://www.npmjs.com/package/findup) or [`find-up`](https://www.npmjs.com/package/find-up) over at [`ghooks`](https://github.com/gtramontina/ghooks) could possibly be an entry point for a possible fix.

**Comment by Wildhammer** [comment]
Is there any way I can achieve this inside package.json? like passing an argument or something
