### ISSUE TITLE
es6 string syntax (backticks) throwing error after clean install  

### ISSUE THREAD

**Issue by raibutera** [commitizen/cz-cli#2]
I've tried using node v0.10.37 (which I figured wasn't likely to work after seeing the backticks) and v0.12.2 (via nvm).. but no matter what i try I can't get `git cz` to execute successfully.

error:
```
Potentially unhandled rejection [2] evalmachine.<anonymous>:80
      commit(`${answers.type}(${answers.scope}): ${answers.subject}`.slice(0,
             ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:73:16)
    at doEval (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:2330:10)
    at __eval (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:2247:7)
    at Loader.exec [as __exec] (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:339:5)
    at load.metadata.execute (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:1182:16)
    at linkDynamicModule (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:668:32)
    at link (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:528:11)
    at Object.execute (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/dist/system.src.js:842:11)
    at doDynamicExecute (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1938:25)
    at link (/Users/rai/.nvm/versions/v0.12.2/lib/node_modules/commitizen/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1986:24)
```

## my .cz.json
{
  "path": "node_modules/cz-conventional-changelog/"
}

**Comment by kytwb** [comment]
Same here :+1:

**Comment by jimthedev** [comment]
Thanks for finding this. I'm using iojs 1.2.0 but will have a look to see why note 0.12 isn't working. 0.10 won't support back ticks so we'd need to transpile somehow.

**Comment by kytwb** [comment]
Can't fork your `cz-conventional-changelog` as it's empty now.

**Comment by raibutera** [comment]
There are like 8 strings. Just write them out with double quotes? Seems a
bit like going Death Star shopping to get rid of the weeds in your back
garden.

Also it's more than a little ironic that a project that is all about best
practices and being a good 'citizen' wasn't tested on the most popular node
version. At all.


I'm only teasing :p. Fantastic idea and I can't wait to use it.

**Comment by jimthedev** [comment]
@raibutera @kytwb Thank you for working on this. The irony of the good citizen mantra is not lost on me.  Thanks for bearing with me! When I created it, I totally forgot that I had switched my nvm global to iojs so this is a bug caused 100% by me and we should probably fix using your much simpler suggestions. :grin:

**Comment by jimthedev** [comment]
cz-conventional-changelog 1.0.1 released. thanks @kytwb!
