### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by adoyle-h** [commitizen/cz-cli#26]
```bash
>(release +) git cz
/Users/ADoyle/.nvm/versions/node/v0.12.2/lib/node_modules/commitizen/src/cli/git-cz.js:1
(function (exports, require, module, __filename, __dirname) { import {configLo
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ADoyle/.nvm/versions/node/v0.12.2/lib/node_modules/commitizen/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ADoyle/.nvm/versions/node/v0.12.2/lib/node_modules/commitizen/bin/git-cz.js:3:1)
    at Module._compile (module.js:460:26)
```

Versions:
node v0.12.2
npm 2.13.3
commitizen 2.0.1

**Comment by jimthedev** [comment]
Thanks. Seems like babel is unhappy being used on global packages. Working on a fix right now.

**Comment by jimthedev** [comment]
@adoyle-h Can you install 2.0.2 to see if it fixes this for you?
