### ISSUE TITLE
SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by jacky810124** [commitizen/cz-cli#266]
I got an error when I type `git cz` in my git repo.

How can I fix it?

```
 git cz
undefined:25
  }
  ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at getContent (/usr/local/lib/node_modules/commitizen/dist/configLoader/getContent.js:47:28)
    at loader (/usr/local/lib/node_modules/commitizen/dist/configLoader/loader.js:39:44)
    at Object.load (/usr/local/lib/node_modules/commitizen/dist/commitizen/configLoader.js:17:35)
    at Object.bootstrap (/usr/local/lib/node_modules/commitizen/dist/cli/git-cz.js:26:70)
    at Object.<anonymous> (/usr/local/lib/node_modules/commitizen/bin/git-cz.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by LinusU** [comment]
What version of node are you running? `node --version`

**Comment by jacky810124** [comment]
the version is: `v4.4.3`

**Comment by jacky810124** [comment]
I can not understand what's happening, but `git cz` can work now..........

**Comment by LinusU** [comment]
That's probably what happened, would have been nice with a better error message though...
