### ISSUE TITLE
git cz fails on node v7.0.0

### ISSUE THREAD

**Issue by safareli** [commitizen/cz-cli#383]
```git cz
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/commitizen/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```
I'm using latest version
```
└─┬ commitizen@2.8.6
  ├─┬ cz-conventional-changelog@1.2.0
  │ ├── conventional-commit-types@2.1.0
  │ ├── lodash.map@4.6.0
  │ ├── pad-right@0.2.2
  │ └── right-pad@1.0.1
  ├── find-node-modules@1.0.3
  ├── glob@7.0.5
  ├─┬ inquirer@1.1.2
  │ └─┬ external-editor@1.1.1
  │   ├─┬ spawn-sync@1.0.15
  │   │ └── os-shim@0.1.3
  │   └── tmp@0.0.29
  ├── lodash@4.15.0
  └── path-exists@2.1.0
```

**Comment by jimthedev** [comment]
Do you have node installed with homebrew or nvm? Looks like others are experiencing a similar issue: https://github.com/nodejs/node/issues/9377

Might have to blow away the node_modules folder?

**Comment by LinusU** [comment]
A clean reinstall fixed this issue for me

**Comment by safareli** [comment]
thanks for pointing to write direction i have just updated node and that was the issue i have removed node_modules (local global) uninstalled node and installed it again
