### ISSUE TITLE
'validate-commit-msg' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by eeasss** [commitizen/cz-cli#446]
Hello,

I am receiving the following error in a lerna-enabled-repo:

```'validate-commit-msg' is not recognized as an internal or external command,```

I get the same error in Git for Windows (2.14.1) and Powershell. This looks like a bug to me, as I am not doing anything special. This same configuration works on Posix systems (OSX and Ubuntu).

We use the cz-lerna-changelog adapter. This is the full callstack

```
'validate-commit-msg' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\xxx\AppData\Roaming\npm\node_modules\commitizen\dist\cli\strategies\git-cz.js:102
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (C:\Users\sergeev\AppData\Roaming\npm\node_modules\commitizen\dist\git\commit.js:50:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by eeasss** [comment]
Turned out to be an issue on our end
