### ISSUE TITLE
[Question] SyntaxError: Parsing JSON at <path> for commitizen config failed:

### ISSUE THREAD

**Issue by Kristinita** [commitizen/cz-cli#465]
### 1. Summary

I can't begin to use commitizen globally in my Windows.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Node.js 9.4.0,
+ npm 5.6.0.

### 3. Steps to reproduce

```shell
D:\SashaBranchReleaseIt>npm install -g commitizen
C:\Users\SashaChernykh\AppData\Roaming\npm\git-cz -> C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\bin\git-cz
C:\Users\SashaChernykh\AppData\Roaming\npm\commitizen -> C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\bin\commitizen
+ commitizen@2.9.6
updated 1 package in 8.143s

D:\SashaBranchReleaseIt>npm install -g cz-conventional-changelog
+ cz-conventional-changelog@2.1.0
updated 1 package in 1.217s

D:\SashaBranchReleaseIt>echo %HOME%
C:\Users\SashaChernykh
```

I create a file `.czrc` in `C:\Users\SashaChernykh` directory. It content:

```json
echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
```

I run `git cz` command in any my git repository.

### 4. Expected behavior

Successful usage `commitizen`.

### 5. Actual behavior

```node
D:\SashaBranchReleaseIt>git cz
C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\configLoader\getContent.js:56
    throw error;
    ^

SyntaxError: Parsing JSON at C:\Users\SashaChernykh\.czrc for commitizen config failed:

    at JSON.parse (<anonymous>)
    at C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\configLoader\getContent.js:40:17
    at readConfigContent (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\configLoader\getContent.js:46:18)
    at getConfigContent (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\configLoader\getContent.js:78:17)
    at loader (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\configLoader\loader.js:62:56)
    at Object.load (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\commitizen\configLoader.js:17:35)
    at Object.bootstrap (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\dist\cli\git-cz.js:26:70)
    at Object.<anonymous> (C:\Users\SashaChernykh\AppData\Roaming\npm\node_modules\commitizen\bin\git-cz.js:2:34)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

Thanks.

**Comment by Kristinita** [comment]
I'm sorry, stupid error.

Valid `.czrc` content is:

```json
{ "path": "cz-conventional-changelog" }
```

Thanks.

**Comment by coolseaman** [comment]
I made stupid mistakes, too.

**Comment by HeartUnchange** [comment]
What is the difference?

**Comment by yinlinyang** [comment]
How to fix it ?

**Comment by jimthedev** [comment]
Try deleting ~/.czrc then putting this in it:

```
{ "path": "cz-conventional-changelog" }
```

**Comment by yinlinyang** [comment]
The .czrc file  content is:  { "path": "cz-conventional-changelog" }. it is still throw error, why?

**Comment by yinlinyang** [comment]
I fixed it . I delete .czrc file and create new one by VScode. 
 .czrc file content: 
`{ "path": "cz-conventional-changelog" }`

**Comment by hxzhao527** [comment]
The difference is the charset. `echo` in Powershell produce ``` .czrc``` with ```UTF-16```, but ```UTF-8``` is expected. So create ```.czrc``` manually with the same content works.

**Comment by hxzhao527** [comment]
@LinusU [load-json-file](https://www.npmjs.com/package/load-json-file) not works.
According to the source code , [index.js#L19](https://github.com/sindresorhus/load-json-file/blob/master/index.js#L19) ,
```javascript
module.exports = (filePath, options) => pify(fs.readFile)(filePath, 'utf8').then(data => parse(data, filePath, options));
module.exports.sync = (filePath, options) => parse(fs.readFileSync(filePath, 'utf8'), filePath, options);
```
It reads content with ```UTF-8```charset instead of ```UTF-16```.
It will throw ```JSONError``` during ```parse```, but the error message is not clear.
```
\node_modules\_parse-json@4.0.0@parse-json\index.js:31
		throw jsonErr;
		^
JSONError: Unexpected token � in JSON at position 0 while parsing near '��{
```

**Comment by dinglittle** [comment]
same question , thanks

**Comment by Ha0ran2001** [comment]
@hxzhao527 谢谢，我删掉命令生成的，自己新建一个就好了
