### ISSUE TITLE
window7 software cmder error

### ISSUE THREAD

**Issue by sumaolin** [commitizen/cz-cli#466]
```
λ git cz
C:\Users\KevinSu\AppData\Roaming\npm\node_modules\commitizen\dist\cli\strategies\git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at C:\Users\KevinSu\AppData\Roaming\npm\node_modules\commitizen\dist\cli\strategies\git-cz.js:87:13
    at C:\Users\KevinSu\AppData\Roaming\npm\node_modules\commitizen\dist\commitizen\staging.js:25:5
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

cmd module is OK

**Comment by jimthedev** [comment]
Did you forget to git add some files?
