### ISSUE TITLE
Remove stack trace from error when committing without staging files

### ISSUE THREAD

**Issue by flyinbutrs** [commitizen/cz-cli#473]
When you run `git cz` when there are no files staged, the error message includes a stack trace. The stack trace is unnecessary and makes a known error look like an unexpected failure.

instead of this:
````
$ git cz
/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at /usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87:13
    at /usr/local/lib/node_modules/commitizen/dist/commitizen/staging.js:25:5
    at ChildProcess.exithandler (child_process.js:263:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
````

It should instead look like this:

````
$ git cz
Error: No files added to staging! Did you forget to run git add?
````

**Comment by LinusU** [comment]
👍 

I usually have a specific error class for errors that are expected, something like this:

```js
class UserError extends Error {}

// ...

main().catch((err) => {
  process.exitCode = 1

  if (err instanceof UserError) {
    console.error(err.message)
  } else {
    console.error(err.stack)
  }
})
```

That way, it's still easy to report errors that are actually a problem with the program, as those will get a full stack trace.

PRs welcome! 🙌

**Comment by plroebuck** [comment]
@LinusU, seems it was fixed last year (PR #437). Why was it never published to NPM?

**Comment by jimthedev** [comment]
@plroebuck Can you try 3.0.1 to see if it looks ok?
