### ISSUE TITLE
add --help flag

### ISSUE THREAD

**Issue by flyinbutrs** [commitizen/cz-cli#474]
Running git `cz --help` should include a help message explaining how to use it.

````
$ git-cz --help
/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at /usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87:13
    at /usr/local/lib/node_modules/commitizen/dist/commitizen/staging.js:25:5
    at ChildProcess.exithandler (child_process.js:263:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
````

**Comment by LinusU** [comment]
Absolutely!

PRs welcome 🙌
