### ISSUE TITLE
Install commitizen failed

### ISSUE THREAD

**Issue by ulivz** [commitizen/cz-cli#556]
## Step to reproduce

1. Run:

```bash
sudo npm install -g commitizen
```

2. Then I got an error:

```
Password:
npm ERR! Unexpected end of JSON input while parsing near '...,"path-exists":"^1.0.'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ulivz/.npm/_logs/2018-08-30T09_14_23_846Z-debug.log
``` 

Content of `/Users/ulivz/.npm/_logs/2018-08-30T09_14_23_846Z-debug.log` is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'commitizen' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session 3d34c4e3148535f2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/commitizen 743ms (from cache)
8 silly pacote tag manifest for commitizen@latest fetched in 783ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule commitizen@2.10.1 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/chalk 561ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/cz-conventional-changelog 563ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/find-root 562ms (from cache)
17 silly pacote version manifest for chalk@1.1.3 fetched in 567ms
18 silly resolveWithNewModule chalk@1.1.3 checking installable status
19 http fetch GET 304 https://registry.npmjs.org/dedent 568ms (from cache)
20 silly pacote version manifest for cz-conventional-changelog@2.0.0 fetched in 570ms
21 silly resolveWithNewModule cz-conventional-changelog@2.0.0 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/cachedir 572ms (from cache)
23 silly pacote version manifest for find-root@1.0.0 fetched in 569ms
24 silly resolveWithNewModule find-root@1.0.0 checking installable status
25 silly pacote version manifest for dedent@0.6.0 fetched in 579ms
26 silly resolveWithNewModule dedent@0.6.0 checking installable status
27 silly pacote range manifest for cachedir@^1.1.0 fetched in 593ms
28 silly resolveWithNewModule cachedir@1.3.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/fs-extra 661ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/inquirer 664ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/detect-indent 669ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/find-node-modules 670ms (from cache)
33 silly pacote range manifest for fs-extra@^1.0.0 fetched in 670ms
34 silly resolveWithNewModule fs-extra@1.0.0 checking installable status
35 silly pacote version manifest for inquirer@1.2.3 fetched in 672ms
36 silly resolveWithNewModule inquirer@1.2.3 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/glob 673ms (from cache)
38 silly pacote version manifest for detect-indent@4.0.0 fetched in 678ms
39 silly resolveWithNewModule detect-indent@4.0.0 checking installable status
40 silly pacote version manifest for find-node-modules@1.0.4 fetched in 679ms
41 silly resolveWithNewModule find-node-modules@1.0.4 checking installable status
42 silly pacote version manifest for glob@7.1.1 fetched in 682ms
43 silly resolveWithNewModule glob@7.1.1 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/lodash 539ms (from cache)
45 silly pacote version manifest for lodash@4.17.5 fetched in 541ms
46 silly resolveWithNewModule lodash@4.17.5 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/minimist 541ms (from cache)
48 silly pacote version manifest for minimist@1.2.0 fetched in 543ms
49 silly resolveWithNewModule minimist@1.2.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/shelljs 516ms (from cache)
51 silly pacote version manifest for shelljs@0.7.6 fetched in 519ms
52 silly resolveWithNewModule shelljs@0.7.6 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/path-exists 597ms (from cache)
54 silly pacote version manifest for path-exists@2.1.0 fetched in 600ms
55 silly resolveWithNewModule path-exists@2.1.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/opencollective 609ms (from cache)
57 silly pacote version manifest for opencollective@1.0.3 fetched in 611ms
58 silly resolveWithNewModule opencollective@1.0.3 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 511ms (from cache)
60 silly pacote version manifest for strip-json-comments@2.0.1 fetched in 512ms
61 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/os-homedir 500ms (from cache)
63 silly fetchPackageMetaData error for os-homedir@^1.0.1 Unexpected end of JSON input while parsing near '...,"path-exists":"^1.0.'
64 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...,"path-exists":"^1.0.'
64 verbose stack     at JSON.parse (<anonymous>)
64 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
64 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
64 verbose stack     at <anonymous>
64 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
65 verbose cwd /usr/local/lib/node_modules
66 verbose Darwin 17.5.0
67 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "commitizen"
68 verbose node v8.11.3
69 verbose npm  v5.6.0
70 error Unexpected end of JSON input while parsing near '...,"path-exists":"^1.0.'
71 verbose exit [ 1, true ]

```

**Comment by jimthedev** [comment]
Guessing this is a transient dependency issue with os-homedir that has since been resolved. Blow away your lock file and try again.
