### ISSUE TITLE
pathspec 'cz' did not match any file(s) known to git

### ISSUE THREAD

**Issue by AlvinYuXT** [commitizen/cz-cli#607]
I am using bootstrap method in a file named cz.js like this

```
const path = require('path')
const bootstrap = require('commitizen/dist/cli/git-cz').bootstrap

bootstrap({
    cliPath: path.join(__dirname, '../node_modules/commitizen'),
    // this is new
    config: {
        path: 'cz-conventional-changelog'
    }
})
```
If I run `node cz.js`. It is correct. 
But when I use them like this:
```
const program = require('commander')
program
    .command('cz')
    .action(() => {
        require('./cz')
    })
```
It shows `error: pathspec 'cz' did not match any file(s) known to git.`
The error info is: 
```

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/Users/yuxitong/worklife/netease/talos/node_modules/commitizen/dist/git/commit.js:46:26)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

**Comment by yorickili** [comment]
Because Git can't recognize cz parameter, please add this line `process.argv.pop();` before `require('./cz')`.

**Comment by AlvinYuXT** [comment]
@yorickili That works for me. Thanks
