### ISSUE TITLE
Cannot find module 'lodash' on latest version 2.4.3

### ISSUE THREAD

**Issue by leonardoanalista** [commitizen/cz-cli#61]
node version 4.2.2

install the latest: `npm install -g commitizen`

modify and add some files then run:  `git cz` 

you get: 
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/leonardo/.nvm/versions/v4.2.2/lib/node_modules/commitizen/dist/commitizen/adapter.js:23:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

I downgraded to version 2.1.0 and works fine.

cheers
Leonardo Correa

**Comment by jimthedev** [comment]
Thanks for reporting this Leonardo. This is my fault. I have lodash listed as a devDependency when it should be a dependency. I will release 2.4.4 shortly to fix this.
