### ISSUE TITLE
Init commitizen encounter SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by KenChoi1992** [commitizen/cz-cli#663]
After running
```
npm install commitizen -g
```
Every thing is good, but when ran
```
commitizen init cz-conventional-changelog --save-dev --save-exact
```
in my project root folder, error occurred  :(
```
/usr/local/lib/node_modules/commitizen/dist/commitizen/commit.js:545
  (0, _git.commit)(sh, repoPath, template, { ...options,
                                             ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/commitizen/dist/commitizen.js:28:38)
    at Module._compile (module.js:571:32)
```
Tried to upgrade npm version to v6.10.3, still got this error, need some help...

**Comment by KenChoi1992** [comment]
Upgrade node to the latest version fix this error. :)
